version: "3.8"

networks:
  order_network:

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - order_network

  broker0:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - "broker0_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_LOG_DIR=/tmp/kafka-logs
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - order_network

  broker1:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9093:9092"
    volumes:
      - "broker1_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LOG_DIR=/tmp/kafka-logs
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - order_network

  broker2:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9094:9092"
    volumes:
      - "broker2_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_LOG_DIR=/tmp/kafka-logs
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - order_network

  order:
    build: ./order
    ports:
      - "8008:80"
    networks:
      - order_network

volumes:
  zookeeper_data:
    driver: local
  broker0_data:
    driver: local
  broker1_data:
    driver: local
  broker2_data:
    driver: local
